#ifndef ERRORCODE_HPP
# define ERRORCODE_HPP

#define		CONTINUE					100
#define		OK							200
#define		NO_CONTENT					204
#define		MOVED_PERMANENTLY			301
#define		BAD_REQUEST					400
#define		UNAUTHORIZED				401
#define 	FORBIDDEN					403
#define		NOT_FOUND					404
#define		METHOD_NOT_ALLOWED			405
#define		REQUEST_TIMEOUT				408
#define		CONFLICT					409
#define		LENGTH_REQUIRED				411
#define		UNSUPPORTED_MEDIA_TYPE		415 
#define		INTERNAL_SERVER_ERROR		500 
#define		NOT_IMPLEMENTED				501 
#define		HTTP_VERSION_NOT_SUPPORTED	505 

#endif